
reviews:
  namespace: student30-bookinfo-dev
  image: ghcr.io/5hoei/bookinfo-reviews
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.dev.opsta.net
  path: "/student30/reviews(/|$)(.*)"
  serviceType: ClusterIP
